server:
  port: 8081
  servlet:
    context-path: /scaffold-order

spring:
  application:
    name: eureka-client-scaffold-order-service

eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/


