spring:
  application:
    name: eureka-scaffold-resource-server
  datasource:
   # 配置数据源
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://47.97.75.100:3306/Guxi_GoGame_db?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: root
      password: guxikeji520
server:
  port: 9070
  servlet:
    context-path: /scaffold-resouce-server

eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/