server:
  port: 9000
spring:
  application:
    name: scaffold-gateway
  redis:
      host: 47.99.112.89
      port: 6379
      password: Zmq745210
      database: 13
eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/ #,http://server2:8002/eureka/,http://server3:8003/eureka/

zuul:
  prefix: /scaffold
  host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
  routes:
    user:
      path: /scaffold-user/**
      serviceId: eureka-client-scaffold-user-service
      strip-prefix: false
    order:
      path: /scaffold-order/**
      serviceId: eureka-client-scaffold-order-service
      strip-prefix: false
    token:
      path: /scaffold-auth-server/**
      serviceId: eureka-client-scaffold-auth-server
      strip-prefix: false
    resouces:
      path: /scaffold-resouce-server/**
      serviceId: eureka-scaffold-resource-server
      strip-prefix: false

  sensitive-headers:
  ratelimit:
      enabled: true
      repository: REDIS
      default-policy-list:
      - limit: 200    #可选 - 每个刷新时间窗口对应的请求数量限制
        quota: 20      #可选-  每个刷新时间窗口对应的请求时间限制（秒）
        refresh-interval: 30 # 刷新时间窗口的时间，默认值 (秒)
        type:
            - url
            - httpmethod

security:
  oauth2:
    client:
      client-id: gateway
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://127.0.0.1:9090/scaffold-auth-server/oauth/token_key