server:
  port: 8080
  servlet:
    context-path: /scaffold-user

spring:
  application:
    name: eureka-client-scaffold-user-service
  datasource:
   # 配置数据源
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://47.97.75.100:3306/Guxi_GoGame_db?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
      username: root
      password: guxikeji520

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000


eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/

mybatis-plus:
  global-config:
    db-config:
      id-type: auto             #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
      map-underscore-to-camel-case: false
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  mapper-locations: classpath:/com/herman/scaffold/dao/mapper/*.xml
  typeAliasesPackage: com.herman.scaffold.model

security:
  oauth2:
    client:
      client-id: userService
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://127.0.0.1:9090/scaffold-auth-server/oauth/token_key